Trungtam/TrungTam/Areas/Admin/Models/CONG_NO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTam.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONG_NO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONG_NO()
        {
            this.CT_CONG_NO = new HashSet<CT_CONG_NO>();
        }
    
        public System.Guid MA_CONG_NO { get; set; }
        public string TEN_CONG_NO { get; set; }
        public Nullable<decimal> TONG_TIEN { get; set; }
        public Nullable<System.DateTime> NGAY_THANH_TOAN { get; set; }
        public System.DateTime NGAY_LAP_CONG_NO { get; set; }
        public string MA_HS { get; set; }
        public Nullable<System.Guid> MA_KM { get; set; }
        public bool TRANG_THAI { get; set; }
    
        public virtual HOC_SINH HOC_SINH { get; set; }
        public virtual KHUYEN_MAI KHUYEN_MAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_CONG_NO> CT_CONG_NO { get; set; }
    }
}

Trungtam/TrungTam/Areas/Admin/Controllers/CONG_NOController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TrungTam.Areas.Admin.Abstracts;
using TrungTam.Areas.Admin.Models;
using Rotativa;
using System.Collections.Generic;
using System.Globalization;

namespace TrungTam.Areas.Admin.Controllers
{
    public class CONG_NOController : Controller
    {
        private QL_TRUNGTAM1Entities db = new QL_TRUNGTAM1Entities();
        public static List<ChiTietCongNo> quanque;
        // GET: Admin/CONG_NO
        //public static List<int> report = null;
        public void ReportsClass(string lop, DateTime dat)
        {
            if (!string.IsNullOrEmpty(lop))
            {
                var tt = (from a in db.CONG_NO
                          join b in db.CT_CONG_NO
                          on a.MA_CONG_NO equals b.MA_CONG_NO
                          where b.MA_LOP.ToString() == lop.ToString()
                          && a.TRANG_THAI == true
                         && a.NGAY_LAP_CONG_NO.Month == dat.Month
                         && a.NGAY_LAP_CONG_NO.Year == dat.Year
                          select b).ToList();
                ViewBag.DaThanhToan = tt.Count();
                ViewBag.TongTien = tt.Sum(n => n.CONG_NO.TONG_TIEN);
                //report.Add(ViewBag.DaThanhToan);
                //report.Add(ViewBag.TongTien);
                if (ViewBag.DaThanhToan == null)
                {
                    ViewBag.DaThanhToan = 0;
                    //report.Add(0);
                }
                if (ViewBag.TongTien == null)
                {
                    ViewBag.TongTien = 0;
                    //report.Add(0);
                }
            }
        }
        public ActionResult Index()
        {
            ViewBag.TongTien = 0;
            ViewBag.DaThanhToan = 0;
            ViewBag.Kiemtra = -1;
            ViewBag.kiemtraChuaHD = -1;
            if (Session["ID"] == null)
                return Redirect("/Home/Index");
            var id = Session["ID"].ToString();
            if (id.First() != '9' && id.First() != '8')
            {
                return Redirect("/Home/Index");
            }
            ViewBag.list_lop = new List<LOP_HOC>();
            var lop = db.LOP_HOC.Where(n => n.TRANG_THAI != -1).Select(n => n.MA_LOP).ToList();
            string lopLast = "";
            if (lop.Count() != 0 && lop != null)
            {
                lopLast = lop.Last().ToString();
                var tienhoc = (from a in db.CT_CONG_NO
                               where a.LOP_HOC.TRANG_THAI != -1 && a.LOP_HOC.MA_LOP.ToString() == lopLast.ToString()
                               && a.CONG_NO.NGAY_LAP_CONG_NO.Month == DateTime.Now.Month
                               && a.CONG_NO.NGAY_LAP_CONG_NO.Year == DateTime.Now.Year
                               select new HS_CongNo
                               {
                                   macongno = a.MA_CONG_NO.ToString(),
                                   tenlop = a.LOP_HOC.TEN_LOP,
                                   mahs = a.CONG_NO.MA_HS,
                                   hoten = a.CONG_NO.HOC_SINH.HO_TEN,
                                   ngaysinh = a.CONG_NO.HOC_SINH.NG_SINH.ToString(),
                                   gioitinh = a.CONG_NO.HOC_SINH.GIOI_TINH,
                                   sdt = a.CONG_NO.HOC_SINH.SDT,
                                   dongia = a.THANH_TIEN,
                                   trangthaihd = a.CONG_NO.TRANG_THAI
                               }).Distinct().ToList();
                ViewBag.list_lop = (from a in db.LOP_HOC
                                    where a.TRANG_THAI != -1
                                    select a).OrderBy(n => n.TEN_LOP).ToList();

                ViewBag.Kiemtra = (from a in db.CONG_NO
                                   join b in db.CT_CONG_NO
                                   on a.MA_CONG_NO equals b.MA_CONG_NO
                                   join c in db.LOP_HOC
                                   on b.MA_LOP equals c.MA_LOP
                                   where c.TRANG_THAI != -1
                                   && a.NGAY_LAP_CONG_NO.Month == DateTime.Now.Month
                                   select a).Count();
                ViewBag.kiemtraChuaHD = (from a in db.CONG_NO
                                         select a).Count();
                ReportsClass(lopLast, DateTime.Now);
                return View(tienhoc);
            }
            //IEnumerable<HS_CongNo> tienhoc = tienhoc1.Distinct();           
            return View();
        }
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index1(string lop)
        {
            string[] str = lop.Split('_');
            var mal = str[0];
            CultureInfo current = CultureInfo.CurrentCulture;
            DateTime dat = Convert.ToDateTime(str[1], System.Globalization.CultureInfo.GetCultureInfo(current.Name).DateTimeFormat);
            //var dat = DateTime.Parse(sa);
            //if (lop.Length > 36)
            //{
            //    dat = DateTime.Parse(lop.Substring(dodai));
            //}

            var n = (from a in db.CT_CONG_NO
                     where a.LOP_HOC.TRANG_THAI != -1 && a.LOP_HOC.MA_LOP.ToString() == mal
                     && a.CONG_NO.NGAY_LAP_CONG_NO.Month == DateTime.Now.Month
                     && a.CONG_NO.NGAY_LAP_CONG_NO.Year == DateTime.Now.Year
                     select new
                     {
                         macongno = a.MA_CONG_NO.ToString(),
                         tenlop = a.LOP_HOC.TEN_LOP,
                         mahs = a.CONG_NO.MA_HS,
                         hoten = a.CONG_NO.HOC_SINH.HO_TEN,
                         ngaysinh = a.CONG_NO.HOC_SINH.NG_SINH.ToString(),
                         gioitinh = a.CONG_NO.HOC_SINH.GIOI_TINH,
                         sdt = a.CONG_NO.HOC_SINH.SDT,
                         dongia = a.THANH_TIEN,
                         trangthaihd = a.CONG_NO.TRANG_THAI,
                         dadong = (from ctcn in db.CT_CONG_NO  ///tổng tiền cần đóng
                                   join cn in db.CONG_NO
                                   on ctcn.MA_CONG_NO equals cn.MA_CONG_NO
                                   where
                                    ctcn.MA_LOP.ToString() == mal
                                   && cn.NGAY_LAP_CONG_NO.Month == dat.Month
                                   && cn.NGAY_LAP_CONG_NO.Year == dat.Year
                                   select ctcn).Sum(cl => cl.THANH_TIEN),

                         hsdong = (from ctcn in db.CT_CONG_NO  ///hocsinh đã đóng
                                   join cn in db.CONG_NO
                                   on ctcn.MA_CONG_NO equals cn.MA_CONG_NO
                                   where
                                    ctcn.MA_LOP.ToString() == mal
                                   && cn.NGAY_LAP_CONG_NO.Month == dat.Month
                                   && cn.NGAY_LAP_CONG_NO.Year == dat.Year
                                   && cn.TRANG_THAI == true
                                   select ctcn).Count(),
                         tiendathu = (from ctcn in db.CT_CONG_NO  ///hocsinh đã đóng
                                      join cn in db.CONG_NO
                                      on ctcn.MA_CONG_NO equals cn.MA_CONG_NO
                                      where
                                       ctcn.MA_LOP.ToString() == mal
                                      && cn.NGAY_LAP_CONG_NO.Month == dat.Month
                                      && cn.NGAY_LAP_CONG_NO.Year == dat.Year
                                      && cn.TRANG_THAI == true
                                      select ctcn).Sum(c => c.THANH_TIEN)
                     }).Distinct().ToList();

            //ReportsClass(mal, dat);
            return Json(n, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Filter1(string id)
        {
            //var dodai = Guid.NewGuid().ToString().Length;
            string[] str = id.Split('_');
            var mal = str[0];
            CultureInfo current = CultureInfo.CurrentCulture;
            DateTime dat = Convert.ToDateTime(str[1], System.Globalization.CultureInfo.GetCultureInfo(current.Name).DateTimeFormat);
            var fil = (from a in db.CT_CONG_NO
                       where a.LOP_HOC.TRANG_THAI != -1 && a.LOP_HOC.MA_LOP.ToString() == mal
                       && a.CONG_NO.NGAY_LAP_CONG_NO.Month == DateTime.Now.Month
                       && a.CONG_NO.NGAY_LAP_CONG_NO.Year == DateTime.Now.Year
                       select new
                       {
                           macongno = a.MA_CONG_NO.ToString(),
                           tenlop = a.LOP_HOC.TEN_LOP,
                           mahs = a.CONG_NO.MA_HS,
                           hoten = a.CONG_NO.HOC_SINH.HO_TEN,
                           ngaysinh = a.CONG_NO.HOC_SINH.NG_SINH.ToString(),
                           gioitinh = a.CONG_NO.HOC_SINH.GIOI_TINH,
                           sdt = a.CONG_NO.HOC_SINH.SDT,
                           dongia = a.THANH_TIEN,
                           trangthaihd = a.CONG_NO.TRANG_THAI,
                           //dadong = (from ctcn in db.CT_CONG_NO
                           //          join cn in db.CONG_NO
                           //          on ctcn.MA_CONG_NO equals cn.MA_CONG_NO
                           //          where
                           //           ctcn.MA_LOP.ToString() == mal
                           //          && cn.NGAY_LAP_CONG_NO.Month == dat.Month
                           //          && cn.NGAY_LAP_CONG_NO.Year == dat.Year
                           //          select ctcn).Sum(cl => cl.THANH_TIEN),
                           dadong = (from ctcn in db.CT_CONG_NO  ///tổng tiền cần đóng

Trungtam/TrungTam/Areas/Admin/Views/CONG_NO/Details.cshtml
@model List<TrungTam.Areas.Admin.Abstracts.ChiTietCongNo>
@{
    ViewBag.Title = "Details";
    var id = Session["ID"];
    if (id.ToString().First().Equals('9'))
    {
        Layout = "~/Areas/Admin/Views/Shared/_layout.cshtml";
    }
    else
    {
        Layout = "~/Areas/Admin/Views/Shared/_layout_vanphong.cshtml";
    }
    var CT_CongNo = (List<TrungTam.Areas.Admin.Abstracts.ChiTietCongNo>)ViewBag.CT_CongNo;
    var KhuyenMai = (List<TrungTam.Areas.Admin.Models.KHUYEN_MAI>)ViewBag.KhuyenMai;
    Nullable<decimal> tong = 0;

    string malop = "";
    int lay = 0;
}

<h2 class="Title_Content">Chi Tiết Học Phí</h2>
<div class="container">
    <div>

        <form role="form" action="/CONG_NO/Create" method="post">
            @Html.AntiForgeryToken();
            <div style="background-color:red;color:black;font-size:medium" class="col-sm-3 p-2 text-white mb-2">Chọn khuyến mãi để thanh toán</div>
            <div>
                <select class="custom-control" name="khuyenmai" id="khuyenmai">
                    <option value="0">Không có</option>
                    @if (KhuyenMai != null)
                    {
                        foreach (var i in KhuyenMai)
                        {
                            <option value="@i.MA_KM">@i.TEN_KM</option>
                        }
                    }
                </select>

            </div>
            <div class="pt-3"> <label class="text-primary">Ngày thanh toán:</label> @DateTime.Now</div>
           
                <table class="table table-bordered table-hover table-responsive">
                    <thead class="text-white bg-primary">
                        <tr>
                            <th>Tên lớp</th>
                            <th>Tên môn</th>
                            <th>Tên loại</th>
                            <th>Tên khối</th>
                            <th>Giá tiền</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (CT_CongNo != null)
                        {
                            foreach (var i in CT_CongNo)
                            {

                                malop += i.malop.ToString();
                                lay++;
                                <tr>
                                    <td>@i.tenlop</td>
                                    <td>@i.tenmon</td>
                                    <td>@i.tenloai</td>
                                    <td>@i.tenkhoi</td>
                                    <td><input type="hidden" name="@i.malop" value="@i.giatien" />@string.Format("{0:0,0}", i.giatien)</td>
                                    @{tong += i.giatien;}
                                </tr>
                            }

                        }
                    </tbody>
                </table>
         

            <input type="hidden" name="malop" id="malop" value="@malop" />
            <input type="hidden" name="lay" value="@lay" />
            <div id="ten"><label class="text-primary mr-2">Ghi chú hóa đơn</label> <br /><textarea name="tencongno" class="text-dark col-sm-4" placeholder="Ghi chú"></textarea></div>
            @{var a = double.Parse(tong.ToString());}
            <div class="col-5 p-2" id="tien"><input type="hidden" name="tongtien" id="tongtien" value="@a" /><span class="text-danger">Tổng tiền: </span>@string.Format("{0:0,0}", tong)</div>
            @if (CT_CongNo != null)
            {
                <input type="hidden" id="mahocsinh" value="@CT_CongNo[0].mahs" />
            }
            @if (CT_CongNo != null)
            {
                <input type="hidden" id="macongno" value="@CT_CongNo[0].macongno" />
            }
            <button class="btn btn-danger" type="button" id="thanhtoan" value="">Thanh toán</button>
        </form>

    </div>
</div>

@section ClientScript{
    <script>

        $('#khuyenmai').change(function () {
            //var token = $("[name='__RequestVerificationToken']").val();
            var khuyenmai = $('#khuyenmai').val();
            if (khuyenmai != "0") {
                $.ajax({
                    url: "/Admin/CONG_NO/KhuyenMai",
                    data: {
        
                        km: khuyenmai
                    },
                    dataType: "JSON",
                    type: "POST",
                    success: function (res) {
                        $('#tien').remove();
                         $('#tiengiam').remove();
                        //$(res).each(function (i, e) {
                            var tong = @a - (@a * res[0] / 100);
                                var di = "<div class='col-5' id='tien'><input type='hidden' name='tongtien' id='tongtien' value='" + tong + "' />Tổng tiền:"  + tong + "</div>";
                            $('#ten').append(di);
                                var dic = "<div class='col-5' id='tiengiam'>Tiền giảm:"  + res[0] + "%</div>";
                            $('#tien').append(dic);
                        //});
                    }
                })
            }
            else {
                $('#tien').remove();
                $('#tiengiam').remove();
                  var di = "<div class='col-5' id='tien'><input type='hidden' name='tongtien' id='tongtien' value='" + @a + "' />Tổng tiền:"  + @a + "</div>";
                  $('#ten').append(di);
            }
        });
        $('#thanhtoan').click(function () {
            bootbox.confirm({
                message: "Bạn có chắc thanh toán hoá đơn hay không?",
                buttons: {
                    confirm: {
                        label: "Có",
                        className: "btn-success"
                    },
                    cancel: {
                        label: "Không",
                        className: "btn-danger"
                    }
                },
                callback: function (result) {
                    var token = $("[name='__RequestVerificationToken']").val();
                    var mahocsinh = $('#mahocsinh').val();
                    var macongno = $('#macongno').val();
                    var makm = $('#khuyenmai').val();
                    var tongtien = $('#tongtien').val();
                    if (result) {
                            @*location.href = '@Url.Action("Payment", "CONG_NO")';*@
                        try {
                            $.ajax({
                            url: "/Admin/CONG_NO/Payment",
                            type: "POST",
                            dataType:"Json",
                            data: {
                                __RequestVerificationToken: token,
                                tong: tongtien,
                                macn: macongno,
                                makm: makm
                            },
                                success: function (res) {
                                    $(res).each(function (i, e) {
                                        bootbox.alert({
                                            message: "Thanh toán thành công hoá đơn ",
                                            callback: function () {
                                                location.href = '@Url.Action("Index", "CONG_NO")';
                                            }
                                        });
                                    });

                                },
                                error: function () {
                                    bootbox.alert("Thanh toán không thành công hoá đơn ");
                                    }
                        });
                        } catch (e) {
                            bootbox.alert("Lỗi vui lòng thử lại sau!!!");
                        }

                    }
                }
            });
        });
    </script>
}

Trungtam/TrungTam/Areas/Admin/Views/CONG_NO/Export_PDF.cshtml
@model List<TrungTam.Areas.Admin.Abstracts.ChiTietCongNo>
@{
    ViewBag.Title = "Export_PDF";
    Layout = "~/Areas/Admin/Views/Shared/_layout_report.cshtml";
    Nullable<decimal> tong = 0;
}

@*<div>TRUNG TÂM </div>*@
<div class="row">
    <div class="col-6">
        <h4> Trung Tâm BDVH <br />KHOA HỌC TRẢI NGHIỆM</h4>
    </div>
    @*<div class="col-1 w-50 h-50" ><img src="~/Asset/admin/img/unnamed.png" /></div>*@
</div>
<div style="text-align:center" class="text-primary"><h4>HÓA ĐƠN</h4></div>
<div style="text-align:right">Ngày thanh toán: @DateTime.Now</div>
@if (Model != null)
{
    <div style="text-align:right;">
        <div class="text-success"><span>Mã học viên: </span>@Model[0].mahs</div>
        <div class="text-success"><span>Tên học viên: </span>@Model[0].tenhs</div>
    </div>
}
<table class="table table-bordered table-hover mt-2">
    <thead class="text-primary">
        <tr>
            <th>Tên lớp</th>
            <th>Tên môn</th>
            <th>Tên loại</th>
            <th>Tên khối</th>
            <th>Giá tiền</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            foreach (var i in Model)
            {

                //malop += i.malop.ToString();
                //lay++;
                <tr>
                    <td>@i.tenlop</td>
                    <td>@i.tenmon</td>
                    <td>@i.tenloai</td>
                    <td>@i.tenkhoi</td>
                    <td><input type="hidden" name="@i.malop" value="@i.giatien" />@string.Format("{0:0,0}", i.giatien)</td>
                    @{tong += i.giatien;}
                </tr>
            }

        }
    </tbody>
</table>
@*<input type="hidden" name="malop" id="malop" value="@malop" />
    <input type="hidden" name="lay" value="@lay" />*@
<div id="ten"><span>Ghi chú hóa đơn</span><textarea name="tencongno" class="text-white col-sm-2" style="text-align:center;" placeholder="Ghi chú"></textarea></div>
<div id="tiengiam" style="text-align:right;">
    @if (Model != null)
    {
        <span>Khuyến mãi: </span>
        @Model[0].tiengiam;
        <span>%</span>
    }
</div>
<div id="tien" style="text-align:right;">
    <input type="hidden" name="tongtien" value="@tong" /><span>Tổng tiền: </span>@string.Format("{0:0,0}", tong)
</div>

@*@if (CT_CongNo != null)
    {
        <input type="hidden" id="mahocsinh" value="@CT_CongNo[0].mahs" />
    }*@
@*</form>*@


@section ClientScript{
    <script>
        @*$('#xuat').click(function () {
              location.href = '@Url.Action("Payment", "CONG_NO")';
        });*@
    </script> }